name: App + Tests CI

on:
  push:
    branches: [ master ]

jobs:
  test-app:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Скачать приложение
      - name: Checkout app repo
        uses: actions/checkout@v4

      # 2. Скачать репо с тестами
      - name: Checkout tests repo
        uses: actions/checkout@v4
        with:
          repository: qa-vmedvedeva/Dictionaty_test
          ref: master
          path: ./
          token: ${{ secrets.TESTS_REPO_TOKEN }}

      # 3. Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 4. Установить зависимости тестов
      - name: Install test deps
        run: |
          pip install -r ./requirements.txt

      - name: Add app to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
        
      # 5. Запустить тесты из другого репо
      - name: Run tests
        run: |
          pytest Dictionaty_test -v
          
      # 6. Node + сборка клиента
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install client deps
        working-directory: ./client
        run: npm install

      - name: Build React app
        working-directory: ./client
        run: npm run build
